services:
  pubg-web:
    build: .
    container_name: pubg-fair
    ports:
      - "8000:8000"
    volumes:
      # 配置文件 - 挂载你极空间上的 config.json
      - ./config.json:/app/config.json:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
