services:
  pubg-web:
    build: .
    ports:
      - "8083:8083"
    volumes:
      - ./config.json:/app/config.json
      - ./pubg_cli_cache.json:/app/pubg_cli_cache.json
    restart: unless-stopped
